name: Environment Variables Workflow
on: [push]
jobs:
    env-vars-and-contxt:
        runs-on: ubuntu-latest
        steps:
            - name: Log ENV VAR
              run: echo $GITHUB_REF
            - name: Log CONTEXT
              run: echo '${{ github.ref }}'