name: Environment Variables Workflow v1
on: [push]

env:
  WF_LEVEL_ENV: Available to all jobs

jobs:
    env-vars-and-contxt:
        runs-on: ubuntu-latest
        # if : $GITHUB_REF = 'refs/heads/main DONT DO THIS'
        if: github.ref == 'refs/heads/main'
        env:
          JOB_LEVEL_ENV: Available to all steps in env-vars-and-context job
        steps:
            - name: Log ENV VAR
              run: echo $GITHUB_REF
            - name: Log CONTEXT
              run: echo '${{ github.ref }}'
            - name: Log Custom ENV Vars
              env:
                STEP_LEVEL_ENV: Available only to this step
                WF_LEVEL_ENV: Overriden in step
              run: |
                echo "STEP_LEVEL_ENV: $STEP_LEVEL_ENV"
                echo "JOB_LEVEL_ENV: $JOB_LEVEL_ENV"
                echo "WF_LEVEL_ENV: $WF_LEVEL_ENV"
