name: First Workflow
on: [push]
     
jobs:
  run-shell-command:
    runs-on : ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello, World!"
      - name: Multiline command
        run: |
          node -v
          npm -v
          echo "This is line 1"
          echo "This is line 2"
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW version
        run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: run-shell-command
    steps:
      - name: Final Step
        run: echo "All previous jobs completed successfully!!!!"
        