name: Manually Triggered Workflow
on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input for manual trigger'
        required: true
        default: 'default value'  
jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Input
        run: |
            echo "The input value is: ${{ github.event.inputs.example_input }}"
      - name: Checkout Repository
        uses: actions/checkout@v3  