name: Static check Functions
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: |
                sleep 20
            - name: Runs on Faulure
            # this step will run only if any of the previous steps have failed
              if: failure()
              run: |
                    echo "This step runs on failure of previous steps."
            - name: Always Runs
            # if: Success() || failure()
              if: always()
              run: |
                    echo "This step always runs regardless of previous step results."
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
          - run: echo 'Job 2'