name: Working Dirs for both Windows and Ubuntu
on: [push]
defaults:
  run:
    shell: bash
jobs:
  display-wd-info-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Display working directory & List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: List files in working directory
        run: ls -la
  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Display working directory & List Files on Windows
        run: |
          Get-Location
          dir -Force
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE